# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2015 Mateusz Kulikowski <mateusz.kulikowski@gmail.com>

obj-$(CONFIG_QCOM_IPQ40XX) += clock-ipq4019.o
obj-$(CONFIG_QCOM_QCM2290) += clock-qcm2290.o
obj-$(CONFIG_QCOM_QCM2290) += sysmap-qcm2290.o
obj-$(CONFIG_SDM845) += clock-sdm845.o
obj-$(CONFIG_SDM845) += sysmap-sdm845.o
obj-$(CONFIG_SDM845) += init_sdm845.o
obj-$(CONFIG_TARGET_DRAGONBOARD820C) += clock-apq8096.o
obj-$(CONFIG_TARGET_DRAGONBOARD820C) += sysmap-apq8096.o
obj-$(CONFIG_TARGET_DRAGONBOARD410C) += clock-apq8016.o
obj-$(CONFIG_TARGET_DRAGONBOARD410C) += sysmap-apq8016.o
obj-y += misc.o
obj-y += clock-snapdragon.o
obj-y += dram.o
obj-y += pinctrl-snapdragon.o
obj-y += pinctrl-apq8016.o
obj-y += pinctrl-apq8096.o
obj-y += pinctrl-ipq4019.o
obj-y += pinctrl-qcm2290.o
obj-y += pinctrl-qcs404.o
obj-y += pinctrl-qrb4210-rb2.o
obj-y += pinctrl-sdm845.o
obj-$(CONFIG_TARGET_QCS404EVB) += clock-qcs404.o
obj-$(CONFIG_TARGET_QCS404EVB) += sysmap-qcs404.o
obj-$(CONFIG_TARGET_QRB4210RB2) += clock-qrb4210-rb2.o
obj-$(CONFIG_TARGET_QRB4210RB2) += sysmap-qrb4210-rb2.o
